(defun appendd (L1 L2)
	(if(null L1) L2
		(cons (car L1) (appendd (cdr L1) L2))
	)
)
(terpri)	
(write "L-1")
(terpri)
(write '(1 2 3))
(terpri)
(terpri)
(write "L-2")
(terpri)
(write '(4 5 6))
(terpri)
(terpri)
(write "after appending")
(terpri)
(write (appendd '(1 2 3) '(4 5 6)))