
(defun pushh(x L)
	(cons x L)
)
(defun peekk(L)
	(car L)
)
(defun popp(L)
	(cdr L)
)
(terpri)
(write "pushing 6 in stack (1 2 3 4 5)")
(terpri)
(write (pushh 6 '(1 2 3 4 5)))
(terpri)
(terpri)
(write "peek value in stack :(1 2 3 4 5) ")
(terpri)
(write (peekk '(1 2 3 4 5)))
(terpri)
(terpri)
(write "pop in the stack (1 2 3 4 5)")
(terpri)
(write (popp '(1 2 3 4 5 )))
